# Generated by Django 2.1.1 on 2018-10-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWeatherDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=25)),
                ('Origin', models.CharField(max_length=25)),
                ('Destination', models.CharField(max_length=25)),
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('Humidity', models.FloatField()),
                ('Pressure', models.FloatField()),
                ('Temperature', models.FloatField()),
                ('Icon', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=250)),
            ],
        ),
    ]
