# Generated by Django 2.1.1 on 2018-10-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myweatherdb',
            name='Country',
            field=models.CharField(default='US', max_length=50),
        ),
        migrations.AddField(
            model_name='myweatherdb',
            name='County',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='myweatherdb',
            name='State',
            field=models.CharField(default='New York', max_length=50),
        ),
        migrations.AlterField(
            model_name='myweatherdb',
            name='City',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myweatherdb',
            name='Description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='myweatherdb',
            name='Destination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myweatherdb',
            name='Icon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='myweatherdb',
            name='Latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='myweatherdb',
            name='Longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='myweatherdb',
            name='Origin',
            field=models.CharField(max_length=50),
        ),
    ]
