# Generated by Django 2.1.1 on 2018-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeather', '0002_auto_20181001_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='myweatherdb',
            name='Temp_max',
            field=models.FloatField(default='75.92'),
        ),
        migrations.AddField(
            model_name='myweatherdb',
            name='Temp_min',
            field=models.FloatField(default='61.52'),
        ),
    ]
